
/* RTK basis data types and error codes */


#ifndef _RTK_BASE_H_
#define _RTK_BASE_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <rtkTypes.h>
#include <arexport.h>

#ifndef __cplusplus
#include <arState.h>
#endif

/* For using this file in Automation Studio tasks, it has to be included AFTER AsDefault.h */
#if defined (_DEFAULT_INCLUDES) && !defined(_RUNTIME_) && !defined(_REPLACE_CONST)
#error Rtk-headers have to be be included after AsDefault.h
#endif


/* Can be used to decorate RTK functions with additional attributes.
 * E.g. #define EXIMPORT __declspec(nothrow) simplifies the function calls for C++,
 * because no exception-related code has to be generated by the compiler */
#ifndef EXIMPORT
	#define EXIMPORT
#endif

/* General definitions for RT kernel */
#define MAX_RTK_NAME_LENGTH 32
#define MAX_RTK_NAME_TERMINATED_LENGTH (MAX_RTK_NAME_LENGTH + 1)

/* Timeout for task events, semaphore, fifo, debugmessage, ... */
#define RTK_TIMEOUT_NOWAIT 0
#define RTK_TIMEOUT_WAITFOREVER 0xFFFFFFFF

typedef void (*LPRTK_CREATE_TASK_FKT)(void* param);

/* Errorcodes */
typedef enum
{
#if !defined(__cplusplus) && !defined(_AR_I386_AUTOMATION_STUDIO_)
	ERR_RTK_OK = ERR_OK,
#else
#ifndef ERR_OK /* could be defined by runtime.h */
	ERR_OK = 0, /* No error	*/
#endif
#endif

	ERR_RTK_OBJID = 25000, /* Invalid object ident */
	ERR_RTK_OBJNOTFOUND,   /* Object with specified name not found */
	ERR_RTK_OBJTYPE,       /* Invalid object type */
	ERR_RTK_OBJ_OVERFLOW,  /* Object table full */
	ERR_RTK_OBJ_EXIST,     /* Object already exists */
	ERR_RTK_OBJNAME,       /* Wrong object name */

	ERR_RTK_PRIORITY = 25010, /* Invalid priority */
	ERR_RTK_NO_STACK,         /* Not enough free stack */
	ERR_RTK_NOT_SUSPENDED,    /* Task is not suspended */
	ERR_RTK_SUSPENDED,        /* Task is already suspended */
	ERR_RTK_TASKVALUE,        /* Invalid valueindex */
	ERR_RTK_NOTASKTIMERS,     /* No more task timers available */
	ERR_RTK_TASKCREATE,       /* OS task not created */
	ERR_RTK_TASKDELETE,       /* OS Task not deleted */

	ERR_RTK_FIFO_CREATE = 25030,   /* FIFO not created (memory alloc, ...) */
	ERR_RTK_FIFO_DELETE,           /* FIFO not deleted (memory free, ...) */
	ERR_RTK_FIFO_WRITE,            /* FIFO not written (fifo full, ...) */
	ERR_RTK_FIFO_READ,             /* FIFO not read (fifo empty, ...) */
	ERR_RTK_FIFO_RELEASE,          /* FIFO not released */
	ERR_RTK_FIFO_ATTACHED_TIMEOUT, /* FIFO read/write with timeout invalid (attached) */
	ERR_RTK_FIFO_NOT_ATTACHED,     /* FIFO not attached when read/write */
	ERR_RTK_FIFO_ATTACHED,         /* FIFO already attached (other task) */
	ERR_RTK_FIFO_ATTACH,           /* FIFO not created for attach */

	ERR_RTK_SEMACREATE = 25040, /* OS semaphore not created */
	ERR_RTK_SEMA_DELETE,        /* OS semaphore not deleted */
	ERR_RTK_SEMA_RELEASE,       /* OS semaphore not released */

	ERR_WRONG_MEMTYPE = 25060, /* Invalid memory type */
	ERR_RTK_NOMEM_HEAP,        /* Not enough memory free in heap */
	ERR_RTK_FREE_HEAP,         /* Memory not in heap */

	ERR_RTK_CREATE_SHAREDMEM, /* SharedMemory not created */
	ERR_RTK_DELETE_SHAREDMEM, /* SharedMemory not deleted */
	ERR_RTK_MAP_SHAREDMEM,    /* SharedMemory not mapped */
	ERR_RTK_UNMAP_SHAREDMEM,  /* SharedMemory not unmapped */

	ERR_RTK_IRQNUMBER = 25080, /* Invalid interruptnumber */
	ERR_RTK_CONNECT_IRQ,       /* Interrupt not connected */
	ERR_RTK_DISCONNECT_IRQ,    /* Interrupt not disconnected */

	ERR_RTK_TIMERCYCLE = 25090, /* Invalid cycletime */
	ERR_RTK_WRONGTIME,          /* Invalid time/date */
	ERR_RTK_SET_RTC,            /* RealTimeClock not set */
	ERR_RTK_TIMER_CREATE,       /* Timer not created */
	ERR_RTK_TIMER_DELETE,       /* Timer not deleted */
	ERR_RTK_TIMER_START,        /* Timer not started */
	ERR_RTK_TIMER_STOP,         /* Timer not stopped */

	/* 25100 - 25199 obsolete (Debugger error codes) */

	ERR_RTK_SOFTPLC_CREATE = 25200, /* RtkCreateSoftPlc not possible */
	ERR_RTK_INIT,                   /* RTK not initialized */
	ERR_RTK_DEINIT,                 /* RTK not deinitialized */
	ERR_RTK_FATAL,                  /* Fatal internal RTK error */
	ERR_RTK_TIMEOUT,                /* Timeout in RTK functions with wait */
	ERR_RTK_NOTSUPPORTED,           /* Function not supported in this RTK version */
	ERR_RTK_UNHANDLED_CPP_EXC,      /* Unhandled CPP Exception */

	ERR_RTK_CRITSECCREATE = 25250, /* CriticalSection not created */
	ERR_RTK_CRITSECDELETE,         /* CriticalSection not deleted */
	ERR_RTK_CRITSECENTER,          /* CriticalSection not enterd */
	ERR_RTK_CRITSECLEAVE,          /* CriticalSection not left */

	ERR_RTK_EXC_BASE = 25300, /* Base for RTK exceptions -> + RTK_EXCTYP_xx */

	ERR_RTK_LOG_CREATE = 25400, /* Log not created */
	ERR_RTK_LOG_DELETE,         /* Log not deleted  */
	ERR_RTK_LOG_NOBUFSET,       /* no Log-Buffer set */
	ERR_RTK_LOG_LOGACTIVE,      /* Log active */
} RTK_ERROR;

/* General datatypes for RT kernel */
typedef ULONG RTK_H;

#ifdef __cplusplus
}
#endif

#endif
